'use strict';
const state={csrf:'',groups:[],schedule:0,preview:null,bookingCursor:null,groupCursor:null,notificationCursor:null,legacyCursor:null};
const attempts=new Map();
const $=id=>document.getElementById(id);
const labels={pending:'Ожидает подтверждения',confirmed:'Подтверждена',declined:'Отклонена',cancelled:'Отменена',completed:'Завершена',planned:'Предварительная дата',manual_contact:'Нужно позвонить',failed:'Не доставлено',sent:'Отправлено',resolved:'Связались'};
const errors={schedule_changed:'Расписание изменил другой сотрудник. Обновите данные, ваш ввод сохранен.',group_changed:'Дата группы изменилась. Обновите список и проверьте новую дату.',booking_changed:'Запись изменил другой сотрудник. Обновите список.',confirmed_conflict:'Следующая группа уже подтверждена. Выберите перенос только этой группы.',date_collision:'На эту дату уже есть группа.',group_full:'В группе нет свободных мест.',capacity_too_small:'Вместимость меньше числа подтвержденных учеников.',invalid_state:'Это действие уже недоступно.',csrf:'Сессия истекла. Обновите страницу.',booking_unconfigured:'Система записи еще не настроена.',admin_unconfigured:'Доступ администратора еще не настроен.',access_required:'Войдите через доступ школы.',invalid_access:'Не удалось проверить доступ.',access_not_allowed:'У вас нет доступа к записям.',invalid_date:'Проверьте дату.',past_date:'Дата должна быть в будущем.'};
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function status(text,error=false){$('status').textContent=text;$('status').className=error?'error':'';}
function button(text,fn,secondary=false){const b=el('button',text,secondary?'secondary':'');b.type='button';b.addEventListener('click',()=>perform(b,fn));return b;}
async function perform(b,fn){b.disabled=true;try{await fn();}catch(e){status(e.message||'Не удалось выполнить действие.',true);}finally{b.disabled=false;}}
function field(label,type,value){const wrap=el('label',label);const input=el('input');input.type=type;input.value=value??'';wrap.append(input);return {wrap,input};}
function selectField(label,options,value){const wrap=el('label',label),input=el('select');for(const [v,text]of options){const option=el('option',text);option.value=v;option.selected=v===String(value);input.append(option);}wrap.append(input);return{wrap,input};}
async function api(path,value,method='POST'){
 const mutation=value!==undefined,serialized=mutation?JSON.stringify(value):undefined,signature=`${method}:${path}:${serialized}`;
 if(mutation&&!attempts.has(signature))attempts.set(signature,crypto.randomUUID());
 let response;
 try{response=await fetch(path,{method:mutation?method:'GET',cache:'no-store',credentials:'same-origin',headers:mutation?{'Content-Type':'application/json','X-CSRF-Token':state.csrf,'Idempotency-Key':attempts.get(signature)}:{Accept:'application/json'},body:serialized,signal:AbortSignal.timeout(10000)});}catch{throw new Error('Связь прервалась. Повторите действие: ключ операции сохранен.');}
 const data=await response.json();
 if(!response.ok){if(response.status<500)attempts.delete(signature);throw new Error(errors[data.error]||`Не удалось выполнить действие (${data.error||response.status}).`);}
 if(mutation)attempts.delete(signature);return data;
}
function dateLabel(date,time){if(!date)return 'Нет даты';const [y,m,d]=date.split('-');return `${d}.${m}.${y}${time?` в ${time}`:''}`;}
async function preview(command){const data=await api('/api/admin/v1/schedule/preview',{...command,expected_revision:state.schedule});state.preview=data;$('preview-dates').replaceChildren();const table=el('table'),head=el('tr');for(const text of ['Было','Станет'])head.append(el('th',text));table.append(head);for(const c of data.changes){const row=el('tr');row.append(el('td',dateLabel(c.old_date,c.old_time)),el('td',c.lifecycle==='cancelled'?'Отменена':dateLabel(c.new_date,c.new_time)));table.append(row);}$('preview-dates').append(table);$('preview-count').textContent=`Затронуто записей: ${data.affected_bookings}. Уведомлений: ${data.notification_count}.`;$('preview-warnings').textContent=data.warnings.join(' ');$('preview').hidden=false;$('commit').focus();status('Проверьте даты перед сохранением.');}
function renderGroup(group){
 const card=el('article',undefined,'card');card.append(el('h3',dateLabel(group.start_date,group.start_time)),el('p',`${group.date_status==='confirmed'?'Старт подтвержден':'Предварительная дата'} · ${group.enrollment_open?'Прием заявок открыт':'Набор закрыт'}`,'badge'),el('p',`Подтверждено: ${group.confirmed_count} из ${group.capacity}. Ожидают: ${group.pending_count}.`));
 const future=group.lifecycle==='scheduled'&&new Date(group.starts_at_utc)>new Date();
 if(!future){card.append(el('p',group.lifecycle==='cancelled'?'Группа отменена':'Группа началась или завершена','meta'));return card;}
 const settings=el('div',undefined,'fields'),capacity=field('Мест','number',group.capacity),dateStatus=selectField('Дата',[['planned','Предварительная'],['confirmed','Подтвержденная']],group.date_status),open=selectField('Прием заявок',[['true','Открыт'],['false','Закрыт']],String(group.enrollment_open));capacity.input.min='1';capacity.input.max='100';settings.append(capacity.wrap,dateStatus.wrap,open.wrap);card.append(settings);
 const actions=el('div',undefined,'actions');actions.append(button('Сохранить настройки',async()=>{await api(`/api/admin/v1/groups/${group.id}`,{expected_revision:group.revision,expected_schedule_revision:state.schedule,capacity:Number(capacity.input.value),date_status:dateStatus.input.value,enrollment_open:open.input.value==='true'},'PATCH');await loadGroups();status('Настройки группы сохранены.');}),button('Список учеников',async()=>{$('filter-group').value=group.id;await loadBookings();$('bookings-section').scrollIntoView({behavior:'smooth'});},true));card.append(actions);
 const move=el('details'),summary=el('summary','Перенести или отменить группу');move.append(summary);const fields=el('div',undefined,'fields'),newDate=field('Новая дата','date',group.start_date),newTime=field('Время','time',group.start_time),scope=selectField('Какие группы',[['one','Только эта'],['following_planned','Эта и следующие предварительные']],'one');fields.append(newDate.wrap,newTime.wrap,scope.wrap);move.append(fields);
 const ack=field('Согласен перенести подтвержденный старт и сделать дату предварительной','checkbox','');ack.input.checked=false;if(group.date_status==='confirmed')move.append(ack.wrap);
 move.append(button('Посмотреть перенос',()=>preview({action:'move',group_id:group.id,new_date:newDate.input.value,new_time:newTime.input.value,scope:scope.input.value,ack_confirmed_move:ack.input.checked})),button('Посмотреть отмену',()=>preview({action:'cancel',group_id:group.id}),true));card.append(move);return card;
}
async function loadGroups(cursor){const data=await api(`/api/admin/v1/groups?history=${$('history').checked}${cursor?`&cursor=${encodeURIComponent(cursor)}`:''}`);state.schedule=data.schedule_revision;state.groupCursor=data.next_cursor;state.groups=cursor?[...state.groups,...data.groups]:data.groups;$('groups').replaceChildren(...state.groups.map(renderGroup));if(!state.groups.length)$('groups').append(el('p','Пока нет групп. Создайте первое расписание.'));$('create-schedule').hidden=state.groups.length>0;const future=state.groups.filter(g=>g.lifecycle==='scheduled'&&new Date(g.starts_at_utc)>new Date());$('append').hidden=!future.length||future.length>=3;$('group-next').hidden=!state.groupCursor;const selected=$('filter-group').value;$('filter-group').replaceChildren(el('option','Все группы'));$('filter-group').firstChild.value='';for(const g of state.groups){const o=el('option',dateLabel(g.start_date,g.start_time));o.value=g.id;$('filter-group').append(o);}$('filter-group').value=selected;}
async function loadBookings(cursor){const params=new URLSearchParams(new FormData($('filters')));if(cursor)params.set('cursor',cursor);const search=params.get('q')?.trim();params.delete('q');const data=search?await api('/api/admin/v1/bookings/search',{...Object.fromEntries(params),q:search}):await api(`/api/admin/v1/bookings?${params}`);state.bookingCursor=data.next_cursor;const nodes=data.bookings.map(b=>{
 const card=el('article',undefined,'card');card.append(el('h3',`${b.public_reference}: ${b.name??'Контакт удален'}`),el('p',b.phone??'Телефон удален'),el('p',`${labels[b.status]||b.status} · ${dateLabel(b.group_start_date,b.group_start_time)}`));if(b.possible_duplicate)card.append(el('p','Возможный дубль по телефону. Проверьте вручную.','notice'));
 const actions=el('div',undefined,'actions');
 const run=async(action,extra={})=>{if(!Number.isInteger(b.group_revision))throw new Error('Не удалось получить группу этой записи. Обновите список.');await api(`/api/admin/v1/bookings/${b.id}/actions`,{action,expected_revision:b.revision,group_revision:b.group_revision,...extra});await Promise.all([loadGroups(),loadBookings()]);status('Запись обновлена. Проверьте доставку уведомления.');};
 if(b.status==='pending'){actions.append(button('Подтвердить',()=>run('confirm')),button('Отклонить',()=>run('decline'),true));}
 if(['pending','confirmed'].includes(b.status))actions.append(button('Отменить запись',()=>run('cancel'),true));
 if(b.status==='confirmed')actions.append(button('Завершить обучение',()=>run('complete'),true));card.append(actions);
 if(['pending','confirmed'].includes(b.status)){const target=selectField('Перенести ученика',state.groups.filter(g=>g.id!==b.group_id&&g.lifecycle==='scheduled'&&g.enrollment_open&&new Date(g.starts_at_utc)>new Date()).map(g=>[g.id,dateLabel(g.start_date,g.start_time)]),'');card.append(target.wrap,button('Перенести в выбранную группу',async()=>{const g=state.groups.find(g=>g.id===target.input.value);if(!g)throw new Error('Выберите группу.');await run('transfer',{target_group_id:g.id,target_group_revision:g.revision});},true));}
 const history=el('div',undefined,'meta');card.append(button('История записи',async()=>{const d=await api(`/api/admin/v1/bookings/${b.id}`);history.replaceChildren(...d.history.map(e=>el('p',`${new Date(e.created_at).toLocaleString('ru-RU')} · ${e.action} · ${e.actor_id}`)));if(!d.history.length)history.append(el('p','Событий нет или срок хранения истек.'));if(d.next_cursor)history.append(el('p','Показаны последние 50 событий.'));},true),history);
 return card;});if(cursor)$('bookings').append(...nodes);else $('bookings').replaceChildren(...nodes);if(!nodes.length&&!cursor)$('bookings').append(el('p','По этому фильтру записей нет.'));$('booking-next').hidden=!state.bookingCursor;}
async function notifications(cursor){const data=await api(`/api/admin/v1/notifications${cursor?`?cursor=${encodeURIComponent(cursor)}`:''}`);const items=data.items??data.notifications??[];state.notificationCursor=data.next_cursor;const nodes=items.map(n=>{const card=el('article',undefined,'card');card.append(el('h3',labels[n.state]||n.state),el('p',`Запись: ${n.booking_id||'анкета'}. Попыток: ${n.attempts}.`));if(n.booking_id)card.append(button('Открыть контакт',async()=>{const d=await api(`/api/admin/v1/bookings/${n.booking_id}`);const b=d.booking??d;card.append(el('p',`${b.name??'Контакт удален'} · ${b.phone??'Телефон удален'}`));},true));const action=async v=>{await api(`/api/admin/v1/notifications/${n.id}/actions`,{action:v,expected_revision:n.revision});await notifications();};card.append(button('Связались по телефону',()=>action('contacted')),button('Повторить уведомление',()=>action('retry'),true));return card;});if(cursor)$('notifications').append(...nodes);else $('notifications').replaceChildren(...nodes);if(!nodes.length&&!cursor)$('notifications').append(el('p','Нет задач для ручной связи.'));$('notification-next').hidden=!state.notificationCursor;}
async function legacy(cursor){const data=await api(`/api/admin/v1/legacy${cursor?`?cursor=${cursor}`:''}`);state.legacyCursor=data.next_cursor;const nodes=data.items.map(b=>{const card=el('article',undefined,'card');card.append(el('h3',`#${b.id}: ${b.name}`),el('p',b.phone),el('p',`Статус: ${b.status} · ${b.created_at}`));return card;});if(cursor)$('legacy').append(...nodes);else $('legacy').replaceChildren(...nodes);if(!nodes.length&&!cursor)$('legacy').append(el('p','Старых заявок нет.'));$('legacy-next').hidden=!state.legacyCursor;}
$('create-schedule').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);perform(e.submitter,()=>preview({action:'create',first_date:f.get('first_date'),start_time:f.get('start_time'),count:Number(f.get('count')),capacity:Number(f.get('capacity'))}));});
$('filters').addEventListener('submit',e=>{e.preventDefault();perform(e.submitter,()=>loadBookings());});
$('reload').addEventListener('click',e=>perform(e.currentTarget,()=>loadGroups()));$('history').addEventListener('change',()=>loadGroups().catch(e=>status(e.message,true)));
$('append').addEventListener('click',e=>perform(e.currentTarget,()=>{const groups=state.groups.filter(g=>g.lifecycle==='scheduled'&&new Date(g.starts_at_utc)>new Date()).sort((a,b)=>a.sequence-b.sequence);return preview({action:'append',last_group_id:groups.at(-1).id});}));
$('commit').addEventListener('click',e=>perform(e.currentTarget,async()=>{if(!state.preview)return;await api('/api/admin/v1/schedule/commit',{normalized_command:state.preview.normalized_command,expected_revision:state.preview.expected_revision});state.preview=null;$('preview').hidden=true;await Promise.all([loadGroups(),loadBookings(),notifications()]);status('Изменение сохранено. Даты доступны сайту и ботам.');}));
$('cancel-preview').addEventListener('click',()=>{$('preview').hidden=true;state.preview=null;});
$('booking-next').addEventListener('click',e=>perform(e.currentTarget,()=>loadBookings(state.bookingCursor)));$('group-next').addEventListener('click',e=>perform(e.currentTarget,()=>loadGroups(state.groupCursor)));
$('notification-refresh').addEventListener('click',e=>perform(e.currentTarget,()=>notifications()));$('notification-next').addEventListener('click',e=>perform(e.currentTarget,()=>notifications(state.notificationCursor)));
$('legacy-refresh').addEventListener('click',e=>perform(e.currentTarget,()=>legacy()));$('legacy-next').addEventListener('click',e=>perform(e.currentTarget,()=>legacy(state.legacyCursor)));
(async()=>{try{const session=await api('/api/admin/v1/session');state.csrf=session.csrf_token;$('actor').textContent=`Выполнен вход: ${session.actor}`;await Promise.all([loadGroups(),loadBookings(),notifications()]);status('Данные загружены.');}catch(e){status(e.message,true);}})();
