import { env } from "cloudflare:test";
import { beforeEach,describe,expect,it,vi } from "vitest";
import { createBookingRouter,verifyTurnstile,type BookingAPIEnv } from "../src/booking-api";
import { AdminDenied,csrfSession } from "../src/admin-auth";
import { commitSchedule,publicGroups } from "../src/groups";
const db=(env as unknown as {DB:D1Database}).DB;
const secret="x".repeat(64);
const config:BookingAPIEnv={DB:db,BOOKING_ENABLED:"true",BOOKING_SECRET:secret,BOOKING_ALLOWED_ORIGINS:"https://avtoshkola.ge",TURNSTILE_SECRET:"turnstile-test",ACCESS_TEAM_DOMAIN:"school.cloudflareaccess.com",ACCESS_AUD:"school",ACCESS_ALLOWED_EMAILS:"staff@example.com",ADMIN_ORIGIN:"https://admin.example.com"};
const captcha=vi.fn(async()=>{});
const route=createBookingRouter({authorize:async r=>{if(r.headers.get('Cf-Access-Jwt-Assertion')!=="test-staff")throw new AdminDenied(401,"access_required");return "staff@example.com";},verifyCaptcha:captcha});
async function seed(){const {scheduleRevision}=await publicGroups(db);await commitSchedule(db,{action:"create",expectedRevision:scheduleRevision,firstDate:"2099-10-05",startTime:"19:00",count:2,capacity:12},crypto.randomUUID(),"staff@example.com",secret);return (await publicGroups(db)).groups[0];}
function request(path:string,value?:object,key=crypto.randomUUID(),origin="https://avtoshkola.ge"){return new Request(`https://admin.example.com${path}`,{method:value?"POST":"GET",headers:{Origin:origin,"Content-Type":"application/json","Idempotency-Key":key,"CF-Connecting-IP":"192.0.2.5"},body:value?JSON.stringify(value):undefined});}
function input(group:{id:string;revision:number}){return{group_id:group.id,group_revision:group.revision,name:"Тест ученик",phone:"+995555123456",consent_version:"booking-v1",consent:true,source:"site_form",turnstile_token:"captcha-token"};}
beforeEach(async()=>{captcha.mockClear();await db.prepare("DELETE FROM booking_rate_limits").run();});
describe("booking HTTP contracts",()=>{
 it("public groups use snake fields/no-store, no PII and work independently of TG",async()=>{await seed();const response=await route(request('/api/v1/groups?service_id=theory_group'),config);expect(response?.status).toBe(200);expect(response?.headers.get('Cache-Control')).toBe('no-store');expect(response?.headers.get('Access-Control-Allow-Origin')).toBe('https://avtoshkola.ge');const data=await response!.json() as any;expect(data.groups[0]).toMatchObject({start_date:'2099-10-05',date_status:'planned',availability:'open'});expect(JSON.stringify(data)).not.toMatch(/phone|name|student_chat/);});
 it("preserves one receipt after response loss and changed CAPTCHA token",async()=>{const g=await seed(),body=input(g),key=crypto.randomUUID();const a=await route(request('/api/v1/bookings',body,key),config);expect(a?.status).toBe(201);const receipt=await a!.json();for(let i=0;i<10;i++){const res=await route(request('/api/v1/bookings',{...body,turnstile_token:`new-token-${i}`},key),config);expect(res?.status).toBe(200);expect(await res!.json()).toEqual(receipt);}expect(captcha).toHaveBeenCalledTimes(1);expect((await db.prepare('SELECT count(*) n FROM bookings').first<any>()).n).toBe(1);expect(Object.keys(receipt as object)).toEqual(['reference','status','message','contact_method']);expect(JSON.stringify(receipt)).not.toContain(body.phone);});
 it("rejects changed business body on an existing key",async()=>{const g=await seed(),body=input(g),key=crypto.randomUUID();await route(request('/api/v1/bookings',body,key),config);const res=await route(request('/api/v1/bookings',{...body,name:'Другой'},key),config);expect(res?.status).toBe(409);expect(await res!.json()).toMatchObject({error:'idempotency_mismatch'});});
 it("rejects spoofed fields, missing consent and disallowed Origin",async()=>{const g=await seed();for(const change of [{student_chat_id:1},{status:'confirmed'},{actor_id:'staff'}]){const r=await route(request('/api/v1/bookings',{...input(g),...change}),config);expect(r?.status).toBe(400);}expect((await route(request('/api/v1/bookings',{...input(g),consent:false}),config))?.status).toBe(400);expect((await route(request('/api/v1/bookings',input(g),crypto.randomUUID(),'https://evil.example'),config))?.status).toBe(403);expect(captcha).not.toHaveBeenCalled();});
 it("limits requests atomically and counts attempts across isolates",async()=>{const g=await seed();for(let i=0;i<6;i++){const r=await route(request('/api/v1/bookings',{...input(g),phone:`+99555512345${i}`}),config);expect(r?.status).toBe(201);}const r=await route(request('/api/v1/bookings',input(g)),config);expect(r?.status).toBe(429);});
 it("requires authorization for lists and CSRF for mutation",async()=>{expect((await route(request('/api/admin/v1/bookings'),config))?.status).toBe(401);const noCsrf=new Request('https://admin.example.com/api/admin/v1/schedule/preview',{method:'POST',headers:{'Cf-Access-Jwt-Assertion':'test-staff',Origin:config.ADMIN_ORIGIN!,'Content-Type':'application/json'},body:'{}'});expect((await route(noCsrf,config))?.status).toBe(403);});
 it("previews and commits structured commands through authenticated API",async()=>{const s=await csrfSession('staff@example.com',config);const groupResponse=await route(new Request('https://admin.example.com/api/admin/v1/groups',{headers:{'Cf-Access-Jwt-Assertion':'test-staff'}}),config);const groups=await groupResponse!.json() as any;const headers={'Cf-Access-Jwt-Assertion':'test-staff','X-CSRF-Token':s.token,Cookie:s.cookie.split(';')[0],Origin:config.ADMIN_ORIGIN!,'Content-Type':'application/json','Idempotency-Key':crypto.randomUUID()};const cmd={action:'create',expected_revision:groups.schedule_revision,first_date:'2099-10-05',start_time:'19:00',count:2,capacity:12};const p=await route(new Request('https://admin.example.com/api/admin/v1/schedule/preview',{method:'POST',headers,body:JSON.stringify(cmd)}),config);expect(p?.status).toBe(200);const preview=await p!.json() as any;expect(preview.changes).toHaveLength(2);const c=await route(new Request('https://admin.example.com/api/admin/v1/schedule/commit',{method:'POST',headers,body:JSON.stringify({expected_revision:preview.expected_revision,normalized_command:preview.normalized_command})}),config);expect(c?.status).toBe(200);expect((await publicGroups(db)).groups).toHaveLength(2);});
 it("rejects oversized JSON and does not claim save on DB failure",async()=>{const r=await route(request('/api/v1/bookings',{...input({id:'unknown',revision:1}),name:'x'.repeat(20000)}),config);expect(r?.status).toBe(413);const broken={...config,DB:{prepare:()=>{throw new Error('private SQL');}} as unknown as D1Database};const res=await route(request('/api/v1/groups'),broken);expect(res?.status).toBe(503);expect(await res!.json()).toEqual({error:'unavailable'});});
 it("validates CAPTCHA server response hostname/action and fails closed",async()=>{const req=request('/api/v1/bookings',{});const fetchMock=vi.fn(async()=>new Response(JSON.stringify({success:true,hostname:'avtoshkola.ge',action:'booking'})));vi.stubGlobal('fetch',fetchMock);try{await verifyTurnstile(req,config,'token');fetchMock.mockImplementation(async()=>new Response(JSON.stringify({success:true,hostname:'evil.example',action:'booking'})));await expect(verifyTurnstile(req,config,'token')).rejects.toMatchObject({code:'captcha_invalid'});}finally{vi.unstubAllGlobals();}});
});

it("admin PII search uses protected JSON body instead of URL",async()=>{
 const g=await seed();await route(request('/api/v1/bookings',input(g)),config);const s=await csrfSession('staff@example.com',config);
 const headers={'Cf-Access-Jwt-Assertion':'test-staff','X-CSRF-Token':s.token,Cookie:s.cookie.split(';')[0],Origin:config.ADMIN_ORIGIN!,'Content-Type':'application/json'};
 const req=new Request('https://admin.example.com/api/admin/v1/bookings/search',{method:'POST',headers,body:JSON.stringify({q:'+995555123456'})});
 expect(req.url).not.toContain('995555');const response=await route(req,config);expect(response?.status).toBe(200);expect((await response!.json() as any).bookings).toHaveLength(1);
 const unsafe=new Request('https://admin.example.com/api/admin/v1/bookings?q=test',{headers});expect((await route(unsafe,config))?.status).toBe(400);
 const unauthorized=new Request(req.url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({q:'+995555123456'})});expect((await route(unauthorized,config))?.status).toBe(401);
});

it("protected booking detail exposes bounded history without contact snapshots",async()=>{
 const g=await seed();await route(request('/api/v1/bookings',input(g)),config);const booking=await db.prepare('SELECT id FROM bookings').first<{id:string}>();
 const req=new Request(`https://admin.example.com/api/admin/v1/bookings/${booking!.id}`,{headers:{'Cf-Access-Jwt-Assertion':'test-staff'}});const response=await route(req,config);expect(response?.status).toBe(200);const data=await response!.json() as any;expect(data.booking.group_revision).toBe(1);expect(data.history).toHaveLength(1);expect(Object.keys(data.history[0]).sort()).toEqual(['action','actor_id','created_at','id']);expect(JSON.stringify(data.history)).not.toContain('+995555123456');expect(data.next_cursor).toBeNull();
 expect((await route(new Request(req.url),config))?.status).toBe(401);
});
